package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.Fingerprint;
import de.greenrobot.daoexample.Metadata;

import de.greenrobot.daoexample.FingerprintDao;
import de.greenrobot.daoexample.MetadataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerprintDaoConfig;
    private final DaoConfig metadataDaoConfig;

    private final FingerprintDao fingerprintDao;
    private final MetadataDao metadataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerprintDaoConfig = daoConfigMap.get(FingerprintDao.class).clone();
        fingerprintDaoConfig.initIdentityScope(type);

        metadataDaoConfig = daoConfigMap.get(MetadataDao.class).clone();
        metadataDaoConfig.initIdentityScope(type);

        fingerprintDao = new FingerprintDao(fingerprintDaoConfig, this);
        metadataDao = new MetadataDao(metadataDaoConfig, this);

        registerDao(Fingerprint.class, fingerprintDao);
        registerDao(Metadata.class, metadataDao);
    }
    
    public void clear() {
        fingerprintDaoConfig.getIdentityScope().clear();
        metadataDaoConfig.getIdentityScope().clear();
    }

    public FingerprintDao getFingerprintDao() {
        return fingerprintDao;
    }

    public MetadataDao getMetadataDao() {
        return metadataDao;
    }

}
