package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.Fingerprint;

import de.greenrobot.daoexample.FingerprintDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerprintDaoConfig;

    private final FingerprintDao fingerprintDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerprintDaoConfig = daoConfigMap.get(FingerprintDao.class).clone();
        fingerprintDaoConfig.initIdentityScope(type);

        fingerprintDao = new FingerprintDao(fingerprintDaoConfig, this);

        registerDao(Fingerprint.class, fingerprintDao);
    }
    
    public void clear() {
        fingerprintDaoConfig.getIdentityScope().clear();
    }

    public FingerprintDao getFingerprintDao() {
        return fingerprintDao;
    }

}
