package de.greenrobot.daoexample;

import com.database.Constants;
import com.strongloop.android.loopback.Model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table METADATA.
 */
public class Metadata extends Model implements Constants{
	
    private Long id;
    private String filename;
    private String title;
    private String artist;
    private String album;
    private String year;
    private String comment;
    private String genre;
    private String duration_seconds;
    private String composer;
    private String composer_2;
    private String compilation;
    private String producer;
    private String usertext;
    private Boolean isdeleted;
    private Integer trackid;
    private Integer cid;
    private java.util.Date uploadeddate;
    private java.util.Date lastuploadeddate;
    private java.util.Date createddate;
    private java.util.Date lastmodifieddate;

    public Metadata() {
    }

    public Metadata(Long id) {
        this.id = id;
    }

    public Metadata(Long id, String filename, String title, String artist, String album, String year, String comment, String genre, String duration_seconds, String composer, String composer_2, String compilation, String producer, String usertext, Boolean isdeleted, Integer trackid, Integer cid, java.util.Date uploadeddate, java.util.Date lastuploadeddate, java.util.Date createddate, java.util.Date lastmodifieddate) {
        this.id = id;
        this.filename = filename;
        this.title = title;
        this.artist = artist;
        this.album = album;
        this.year = year;
        this.comment = comment;
        this.genre = genre;
        this.duration_seconds = duration_seconds;
        this.composer = composer;
        this.composer_2 = composer_2;
        this.compilation = compilation;
        this.producer = producer;
        this.usertext = usertext;
        this.isdeleted = isdeleted;
        this.trackid = trackid;
        this.cid = cid;
        this.uploadeddate = uploadeddate;
        this.lastuploadeddate = lastuploadeddate;
        this.createddate = createddate;
        this.lastmodifieddate = lastmodifieddate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getDuration_seconds() {
        return duration_seconds;
    }

    public void setDuration_seconds(String duration_seconds) {
        this.duration_seconds = duration_seconds;
    }

    public String getComposer() {
        return composer;
    }

    public void setComposer(String composer) {
        this.composer = composer;
    }

    public String getComposer_2() {
        return composer_2;
    }

    public void setComposer_2(String composer_2) {
        this.composer_2 = composer_2;
    }

    public String getCompilation() {
        return compilation;
    }

    public void setCompilation(String compilation) {
        this.compilation = compilation;
    }

    public String getProducer() {
        return producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public String getUsertext() {
        return usertext;
    }

    public void setUsertext(String usertext) {
        this.usertext = usertext;
    }

    public Boolean getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    public Integer getTrackid() {
        return trackid;
    }

    public void setTrackid(Integer trackid) {
        this.trackid = trackid;
    }

    public Integer getCid() {
        return cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public java.util.Date getUploadeddate() {
        return uploadeddate;
    }

    public void setUploadeddate(java.util.Date uploadeddate) {
        this.uploadeddate = uploadeddate;
    }

    public java.util.Date getLastuploadeddate() {
        return lastuploadeddate;
    }

    public void setLastuploadeddate(java.util.Date lastuploadeddate) {
        this.lastuploadeddate = lastuploadeddate;
    }

    public java.util.Date getCreateddate() {
        return createddate;
    }

    public void setCreateddate(java.util.Date createddate) {
        this.createddate = createddate;
    }

    public java.util.Date getLastmodifieddate() {
        return lastmodifieddate;
    }

    public void setLastmodifieddate(java.util.Date lastmodifieddate) {
        this.lastmodifieddate = lastmodifieddate;
    }

}
